services:
  - type: web
    name: comunidad-rover-app-backend
    runtime: node
    region: oregon

    rootDir: backend

    buildCommand: npm install && npm run build
    startCommand: npm run start:prod

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Añade DATABASE_URL en el Dashboard de Render (Environment) con tu connection string de Neon (Neon DB)
      - key: DATABASE_URL
        sync: false

  - type: static_site
    name: comunidad-rover-app-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      # URL pública del backend (se completa desde el panel de Render una vez creado el backend)
      - key: VITE_API_URL
        sync: false
